name: Rest/Noise
favicon: null
layout_spectrum: 1
typography_spectrum: 0.23521
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f6f6f4'
    - '#000002'
    - '#00282e'
    - '#778890'
    - '#415c67'
  brandStrength: 0.6875
  lightness: 0.375
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
